apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: confluence
  namespace: confluence
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: confluence.qoocar.com
    http:
      paths:
      - backend:
          serviceName: confluence-svc
          servicePort: 8090
   
