{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "zookeeper.serviceAccountName" . }}
  labels: {{- include "zookeeper.labels" . | nindent 4 }}
    role: zookeeper
{{- end }}
