apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunx-xxl
  namespace: sunx-prod
spec:
  selector:
    matchLabels:
      app: sunx-xxl
  template:
    metadata:
      labels:
        app: sunx-xxl
    spec:
      containers:
      - name: sunx-xxl
        image: xuxueli/xxl-job-admin:2.2.0
        ports:
        - containerPort: 8080
        env:
        - name: PARAMS
          value: "--spring.datasource.url=jdbc:mysql://sunx-mysql:32307/sunxx_job?Unicode=true&characterEncoding=UTF-8&useSSL=false --spring.datasource.username=root --spring.datasource.password=root --spring.mail.username=23218371@qq.com --spring.mail.password=yb19750503"
---
apiVersion: v1
kind: Service
metadata:
  name: sunx-xxl
  namespace: sunx-prod
  labels:
    app: sunx-xxl
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32322
    protocol: TCP
    name: http
  selector:
    app: sunx-xxl