apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-nginx
  namespace: monitoring
  labels:
    k8s-app: ingress-nginx
    component: ingress-nginx
    heritage: Tiller
    prometheus: kube-prometheus
    release: kube-prometheus
spec:
  jobLabel: k8s-app
  endpoints:
  - interval: 30s
    port: metrics
  selector:
    matchLabels:
      k8s-app: ingress-nginx
  namespaceSelector:
    matchNames:
    - ingress-nginx
