kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: nexus3
  name: nexus3
  namespace: public-nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus3
  template:
    metadata:
      labels:
        app: nexus3
    spec:
      containers:
        - name: nexus3
          image: sonatype/nexus3:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8081
            protocol: TCP
          volumeMounts:
          - name: public-nexus-data
            mountPath: /nexus-data
      volumes:
        - name: public-nexus-data
          persistentVolumeClaim:
            claimName: public-nexus-pvc

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: nexus3
  name: nexus3
  namespace: public-nexus
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: nexus3