apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jira
  namespace: jira
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: jira.qoocar.com
    http:
      paths:
      - backend:
          serviceName: jira-svc
          servicePort: 8080
   
